#!/bin/bash

# Obtenha a janela ativa
ICON_PATH=$HOME/dotfiles/config/eww/icon-cache
WINDOW_ID=$(xprop -root _NET_ACTIVE_WINDOW | awk '{print $5}')

#!/bin/bash
if [[ "$1" == '--help' ]]; then
    echo "Show information or extract a window's icons to NAME-WIDTH.png"
    echo "Usage: ${0##*/} [NAME]"
    exit
fi

if [[ "$1" ]]; then
    cmd=(convert - "$ICON_PATH/${1}.png")
else
    cmd=(identify -)
fi

split_icons() {
    xprop -id $WINDOW_ID -notype 32c _NET_WM_ICON |
    awk -v RS=', | = ' '
        NR == 1         { h  = $1; i++; next }
        NR == i + 1     { x  = $1;        printf "%s = %s", h, x; next }
        NR == i + 2     { s  = x * $1 } { printf ", %s", $1 }
        NR == i + 2 + s { i += s + 2;     printf "\n" }
    '
}

to_pam() {
    perl -0777 -pe '@_=/\d+/g;
    printf "P7\nWIDTH %d\nHEIGHT %d\n", splice@_,0,2;
    printf "DEPTH 4\nMAXVAL 255\nTUPLTYPE RGB_ALPHA\nENDHDR\n";
    $_=pack "N*", @_;
    s/(.)(...)/$2$1/gs'
}

while read -r data; do to_pam <<< "$data" | "${cmd[@]}"; done < <(split_icons)