#!/bin/sh

python -u "$(dirname $0)/notification/notification-watchdog.py" | while read -r line; do
    # Gera ID único com timestamp em nanosegundos
    id=$(date +%s%N)
    
    # Adiciona timestamp, id e datetime ao objeto da notificação
    datetime=$(date '+%d/%m/%y %H:%M')
    notification=$(echo "$line" | jq -c ". + {id: \"$id\", timestamp: $(date +%s), datetime: \"$datetime\"}")
    
    # Lê o array atual do eww
    current=$(eww get notification_status | jq -c '.')
    
    # Adiciona a nova notificação no início do array (mais recente primeiro)
    updated=$(echo "$current" | jq -c ". |= ([$notification] + .)")
    
    # Atualiza eww com JSON cru
    eww update notification_status="$updated"
    eww update notification_count=$(($(eww get notification_count) + 1))
done