#!/bin/sh

# Verifica status do player
player_status=$(playerctl status 2>/dev/null)
if [ "$player_status" = "No players found" ] || [ -z "$player_status" ]; then
    exit 0
fi

# Captura todos os metadados de uma vez
metadata=$(playerctl metadata --format \
'{
    "artUrl": "{{ mpris:artUrl }}",
    "artist": "{{ artist }}",
    "album": "{{ album }}",
    "title": "{{ title }}",
    "position": "{{ position }}",
    "length": "{{ mpris:length }}"
}')

# Json extract and asserts / exception handling
imageUrl=$(echo "$metadata" | jq -r .artUrl)

position=$(echo "$metadata" | jq -r .position)
(( position=position )) # int assert

length=$(echo "$metadata" | jq -r '.length')
if [[ -z "$length" ]]; then
    length=1
fi
(( length=length )) # int assert

artist=$(echo "$metadata" | jq -r .artist)
album=$(echo "$metadata" | jq -r .album)
title=$(echo "$metadata" | jq -r .title)

# Calcula posição e duração em formato de texto
positionText=$(printf "%d:%02d" $((position / 1000000 / 60)) $((position / 1000000 % 60)))
lengthText=$(printf "%d:%02d" $((length / 1000000 / 60)) $((length / 1000000 % 60)))

# Calcula porcentagem de progresso
playPercent=$((position * 100 / length))

# Define caminho para a imagem
filename=$(basename "$imageUrl")
filePath="/tmp/player-${filename}"
if [ -z "$filename" ]; then
    filePath=""
fi

# Exibe JSON formatado com todas as informações
echo '{
    "artUrl": "'"$filePath"'",
    "artist": "'"$artist"'",
    "album": "'"$album"'",
    "title": "'"$title"'",
    "position": "'"$position"'",
    "positionText": "'"$positionText"'",
    "length": "'"$length"'",
    "lengthText": "'"$lengthText"'",
    "status": "'"$player_status"'",
    "playPercent": "'"$playPercent"'"
}'

# Baixa a imagem se ainda não existir
if [ ! -z "$filePath" ]; then
    if [ ! -e "$filePath" ]; then
        curl -s -o "$filePath" "$imageUrl"
    fi
fi