#!/bin/sh
current_user=$(whoami)
password_input=$1

# Atualiza a mensagem do lockscreen
eww update lockscreen-input-active=false
eww update lockscreen-message="Verificando..."

on_wrong_password() {
    sleep 3
    eww update lockscreen-input-active=true
    eww update lockscreen-message="Senha incorreta."
    sleep 5
    eww update lockscreen-message=""
}

( on_wrong_password ) &
sleep_pid=$!

on_right_password() {
    kill $sleep_pid
    eww close lock-screen
    hyprctl dispatch submap default > /dev/null 2>&1
}

echo "$password_input" | su -c "true" "$current_user" > /dev/null 2>&1

# Captura o código de saída do su
result=$?

# Verifica se o comando foi bem-sucedido
if [ $result -eq 0 ]; then
    on_right_password
fi

# Reseta o campo de senha e mensagem
eww update lockscreen-input-active=true
eww update lockscreen-message=""
eww update lockscreen-password-input=""