#!/bin/bash
echo '{"window_title":"","window_class":""}'

# For i3wm
    #i3-msg -t subscribe -m '["window","workspace"]' | while read -r line; do
# For bspwm
bspc subscribe | while read -r line; do
    # Obter o ID da janela focada
    window_id=$(xprop -root | grep "_NET_ACTIVE_WINDOW(WINDOW):" | awk '{print $5}')

    if [ "$window_id" == "0x0" ]; then
        echo '{"window_title":"","window_class":""}'
    else
        window_class=$(xdotool getwindowclassname $window_id)
        window_title=$(xdotool getwindowname $window_id)

        echo '{"window_title":"'$window_title'","window_class":"'$window_class'"}'
    fi
done